### ISSUE TITLE
No file is generated when ackgen output path contains subdirectories

### ISSUE THREAD

**Issue by appdev-exaring** [MartinP7r/AckGen#4] opened 2022-02-02 10:52 UTC
Currently the generation of the output file via a "Run Script" phase fails if the path contains subdirectories:

(From the Run Script Phase)

- Works: `swift run ackgen $SRCROOT/Acknowledgements.plist`
- Fails (no file is generated): `swift run ackgen $SRCROOT/subfolder/Acknowledgements.plist`

**Comment by MartinP7r** [comment] 2023-03-11 10:07
@appdev-exaring thank you for getting in touch.  
That's interesting. I'm actually keeping my `Acknowledgements.plist` in a subdirectory.  
Could you check if your `subfolder` actually exists? I haven't checked, but I don't think it will create intermediate directories automatically.  

Also, if that isn't the cause. Could you please check the build in your Xcode's Report Navigator for any errors?

**Comment by MartinP7r** [comment] 2023-04-15 22:30
Closing this for now. @appdev-exaring please feel free to reopen if you tried the above without success.

**Closed by MartinP7r** 2023-04-15 22:30 UTC
Labels: bug
